[tool.poetry]
name = "nuitka-conflict-bug"
version = "0.1.0"
description = ""
authors = ["Zaid Bouslikhin <zaid@mx3d.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
nuitka = "^2.4.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
